[build]
builder = "NIXPACKS"
buildCommand = "yarn build"

[deploy]
numReplicas = 1
startCommand = "yarn serve"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
envs = [
  { name = "PORT", default = "3000" },
]

[[services.ports]]
port = 3000
internal = false
protocol = "http"

[variables]
VUE_APP_API_URL = "https://sms-activate-platform-production.up.railway.app"
PORT = "3000" 